POST http://localhost:5000/api/salads HTTP/1.1
Content-Type: application/json

{
    "name": "New Salad",
    "weight": 2,
    "ingredients": ["potato", "tomato", "chicken"],
    "sauce": "mayonnaise",
    "dietType": "none",
    "isSpicy": false,
    "expired": "2023-10-30"
}